/*
 * Copyright Curtin University, 2015.
 */
// DO NOT MODIFY THIS FILE BY HAND. IT WAS GENERATED BY generate_orm_files.py
package au.edu.curtin.lims.db.hibernate4;

import javax.inject.Inject;

import au.edu.curtin.lims.db.ITestRepository;
import au.edu.curtin.lims.domain.Test;

import org.hibernate.SessionFactory;

import org.springframework.stereotype.Repository;

@Repository
public class HibernateTestRepository extends BaseHibernateRepository<Test> implements ITestRepository {
    @Inject
    public HibernateTestRepository(SessionFactory sessionFactory) {
        super(Test.class, sessionFactory);
    }

    public Test save(Test test) {
        this.currentSession().save(test);
        return test;
//        return new Test(
//            (Integer) id,
//            test.getUsername(),
//            test.getPassword(),
//            test.getEnabled()
//);
    }
}
